version: "3.7"
services:
  prom:
    image: prom/prometheus
    volumes:
      - ./conf/:/conf
    command: "--config.file=/conf/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prom