version: "3.7"
networks:
  promnet:
    driver: bridge

services:
  prom:
    image: prom/prometheus
    volumes:
      - ./conf/:/conf
      - ./data/prometheus:/data
    command:
      - '--config.file=/conf/prometheus.yml'
      - '--storage.tsdb.path=/data'
    ports:
      - 9090:9090
    depends_on:
      - alertmanager
    networks:
      - promnet

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./conf/:/conf
      - ./data/alertmanager:/data
    command:
      - '--config.file=/conf/alertmanager.yml'
      - '--storage.path=/data'
    ports:
      - 9093:9093
    networks:
      - promnet
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - promnet

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prom

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: HOST_IP
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    volumes:
      - ./data/kafka/docker.sock:/data/kafka/docker.sock
    depends_on:
      - zookeeper
