server:
  port: 8082

spring:
  application:
    name: ResponderApplication
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

  metrics:
    export:
      prometheus:
        enabled: true
